version: '3'

includes:
  frontend:
    taskfile: ./frontend/Taskfile.yml
    dir: ./frontend

  simple:
    taskfile: ./variants/simple/Taskfile.yml
    dir: ./variants/simple

  simple-backend:
    taskfile: ./variants/simple/backend/Taskfile.yml
    dir: ./variants/simple/backend

  simple-rs:
    taskfile: ./variants/simple-rs/Taskfile.yml
    dir: ./variants/simple-rs

  simple-rs-backend:
    taskfile: ./variants/simple-rs/backend/Taskfile.yml
    dir: ./variants/simple-rs/backend

  distributed:
    taskfile: ./variants/distributed/Taskfile.yml
    dir: ./variants/distributed

  distributed-backend:
    taskfile: ./variants/distributed/backend/Taskfile.yml
    dir: ./variants/distributed/backend

  bench:
    taskfile: ./bench/Taskfile.yml
    dir: .

tasks:
  default:
    desc: 利用できるタスクを一覧表示する
    cmds:
      - task --list-all
    silent: true

  down:all:
    desc: すべてのバックエンド構成を停止し、ボリュームを削除する
    cmds:
      - task simple:down
      - task simple-rs:down
      - task distributed:down
