version: '3'

tasks:
  up:
    cmds:
      - docker compose -f compose.yaml up -d --build

  up:scaled:
    cmds:
      - docker compose -f compose.yaml up -d --build --scale backend=3

  down:
    cmds:
      - docker compose -f compose.yaml down

  logs:
    cmds:
      - docker compose -f compose.yaml logs -f
